version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
    command: npm run dev
    environment:
      NODE_ENV: development

  frontend:
    volumes:
      - ./frontend:/app
    command: npm run dev
    environment:
      NODE_ENV: development 