
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: bywayuser
      POSTGRES_PASSWORD: bywaypass
      POSTGRES_DB: bywaydb
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/rashinkp/byway/backend:${COMMIT_SHA:-latest}
    depends_on:
      - db
    env_file:
      - ./backend.env
    environment:
      DATABASE_URL: postgres://bywayuser:bywaypass@db:5432/bywaydb
      NODE_ENV: production
    ports:
      - "5001:5001"
    restart: always

  frontend:
    image: ghcr.io/rashinkp/byway/frontend:${COMMIT_SHA:-latest}
    depends_on:
      - backend
    env_file:
      - ./frontend.env
    environment:
      NEXT_PUBLIC_API_URL: https://byway.ddns.net/api/v1
      NEXT_PUBLIC_SOCKET_URL: https://byway.ddns.net
      NODE_ENV: production
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: 212202057591-87b5i5r366ss61n3nkdjmj5kksaudt8r.apps.googleusercontent.com
    ports:
      - "3000:3000"
    restart: always

volumes:
  db_data:

# ---
# DB data is persisted in the named volume 'db_data'.
# To safely clean up unused Docker images, containers, and networks (but NOT volumes/data), run:
#   docker system prune -a -f
# This will keep your database data safe.
# To also clean up old logs, you can run:
#   sudo journalctl --vacuum-time=7d
#   sudo rm -rf /var/lib/docker/containers/*/*-json.log
# ---