
services:
  backend:
    image: ghcr.io/rashinkp/byway/backend:${COMMIT_SHA:-latest}
    env_file:
      - ./backend/.env.production
    environment:
      NODE_ENV: production
    ports:
      - "5001:5001"
    restart: always

  frontend:
    image: ghcr.io/rashinkp/byway/frontend:${COMMIT_SHA:-latest}
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.production
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: always

# ---
# Database has been migrated to external service.
# No local database volume is needed anymore.
# To clean up unused Docker resources, run:
#   docker system prune -a -f
# To also clean up old logs, you can run:
#   sudo journalctl --vacuum-time=7d
#   sudo rm -rf /var/lib/docker/containers/*/*-json.log
# ---