services:
  backend:
    volumes:
      - ./backend:/app
    command: npm run dev
    environment:
      NODE_ENV: development
    env_file:
      - ./backend/.env.development

  frontend:
    volumes:
      - ./frontend:/app
    command: npm run dev
    environment:
      NODE_ENV: development
    env_file:
      - ./frontend/.env.development 