name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache frontend node_modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-node-modules-

      - name: Cache backend node_modules
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-node-modules-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-node-modules-

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build and push images sequentially to reduce disk usage and avoid 'no space left on device' errors
      - name: Build and push frontend image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
          LATEST_IMAGE: ghcr.io/${{ github.repository }}/frontend:latest
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_SOCKET_URL: ${{ secrets.NEXT_PUBLIC_SOCKET_URL }}
          NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
          NEXT_PUBLIC_GOOGLE_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_GOOGLE_REDIRECT_URI }}
          NEXT_PUBLIC_FACEBOOK_APP_ID: ${{ secrets.NEXT_PUBLIC_FACEBOOK_APP_ID }}
          NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
        run: |
          cd frontend
          npm cache clean --force
          docker builder prune -af || true
          docker build --no-cache \
            --build-arg NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
            --build-arg NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL \
            --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID \
            --build-arg NEXT_PUBLIC_GOOGLE_REDIRECT_URI=$NEXT_PUBLIC_GOOGLE_REDIRECT_URI \
            --build-arg NEXT_PUBLIC_FACEBOOK_APP_ID=$NEXT_PUBLIC_FACEBOOK_APP_ID \
            --build-arg NEXT_PUBLIC_PAYPAL_CLIENT_ID=$NEXT_PUBLIC_PAYPAL_CLIENT_ID \
            --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY \
            -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $LATEST_IMAGE
          docker push $IMAGE_NAME
          docker push $LATEST_IMAGE

      # Wait for frontend build to finish before starting backend
      - name: Build and push backend image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          LATEST_IMAGE: ghcr.io/${{ github.repository }}/backend:latest
        run: |
          cd backend
          npm cache clean --force
          docker builder prune -af || true
          docker build --no-cache -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $LATEST_IMAGE
          docker push $IMAGE_NAME
          docker push $LATEST_IMAGE

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          REPO_NAME: ${{ github.repository }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
          cat > deploy.sh << 'EOF'
          #!/bin/bash
          set -e
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          export COMMIT_SHA=${{ github.sha }}
          # ---
          # CLEANUP: Free up disk space before pulling new images
          # Remove unused Docker images, stopped containers, networks, and builder cache (safe for DB data)
          docker system prune -a -f
          docker builder prune -a -f
          # Optional: Clean up old Docker/container logs (safe for DB data)
          sudo journalctl --vacuum-time=7d || true
          sudo rm -rf /var/lib/docker/containers/*/*-json.log || true
          # ---
          docker compose -f docker-compose.yml pull
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up -d
          EOF
          scp -i key.pem -o StrictHostKeyChecking=no docker-compose.yml ${EC2_USER}@${EC2_HOST}:~/app/
          scp -i key.pem -o StrictHostKeyChecking=no deploy.sh ${EC2_USER}@${EC2_HOST}:~/app/
          ssh -i key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
            cd ~/app
            chmod +x deploy.sh
            ./deploy.sh
          EOF
          rm key.pem deploy.sh